/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package resortbooking;

/**
 *
 * @author Leong
 */


import com.google.common.collect.Lists;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.io.FileWriter; 


public class viewBooking extends javax.swing.JFrame {

    /**
     * Creates new form viewBooking
     */
//get variable from another jframe
    public viewBooking(int rowmouseevent) {
        
        initComponents();
        //using try and catch method to handle exception
        try{
            
            //create file and scanner to read text file
            File f = new File("booking.txt");
            Scanner s = new Scanner(new File("booking.txt"));
            
            //create a new list and use while loop to add data into the list
            List<String> info = new ArrayList<>();
            
            while(s.hasNext()){
                info.add(s.next());
            }
            
            //declare the partition as 8
            int listsize = 8;
            
            //separte list2 and 8 element in each part
            List<List<String>> list2 = Lists.partition(info, listsize);
            
            //declare size of list
            int size = list2.size();
            
            //declare a table model
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            
            //using for loop to add date into table
            int index;
            for(index = 0;index<size;index++){
                String data1 = list2.get(index).get(0);
                String data2 = list2.get(index).get(1);
                String data3 = list2.get(index).get(2);
                String data4 = list2.get(index).get(3);
                String data5 = list2.get(index).get(4);
                String data6 = list2.get(index).get(5);
                String data7 = list2.get(index).get(6);
                String data8 = list2.get(index).get(7);
                
                Object[] row = { data1, data2, data3, data4, data5, data6, data7, data8 };
                model.addRow(row);

            }
        }catch(Exception e){}
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        deletebutt = new javax.swing.JButton();
        EditButt = new javax.swing.JButton();
        backbutt = new javax.swing.JButton();
        receiptbutt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room No", "Check In Date", "Check Out Date", "Total Price", "Name", "Email", "Phone No", "IC Number"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        deletebutt.setText("Delete");
        deletebutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttActionPerformed(evt);
            }
        });

        EditButt.setText("Edit");
        EditButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtActionPerformed(evt);
            }
        });

        backbutt.setText("Back");
        backbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttActionPerformed(evt);
            }
        });

        receiptbutt.setText("View Receipt");
        receiptbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptbuttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(deletebutt)
                        .addGap(90, 90, 90)
                        .addComponent(receiptbutt)
                        .addGap(84, 84, 84)
                        .addComponent(EditButt, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(backbutt)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletebutt)
                    .addComponent(EditButt)
                    .addComponent(receiptbutt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backbutt)
                .addGap(14, 14, 14))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deletebuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttActionPerformed
        //using try and catch to handle exception    
        try{
                 //get selected row from table when mouse click
                int rowmouseevent = jTable1.getSelectedRow();

                //create file and scanner to read text file
                File f = new File("booking.txt");
                Scanner s = new Scanner(new File("booking.txt"));
                
                //create list and while loop to add date into list
                List<String> info = new ArrayList<>();
                while(s.hasNext()){
                    info.add(s.next());
                }
                
                //declare partition as 8 and separte list in to part with 8 element in each part
                int listsize = 8;
                List<List<String>> list2 = Lists.partition(info, listsize);

                //declare variable
                int index,index2,index3;
                
                //if rowmouseevent is not -1 then proceed
                if(rowmouseevent!=-1){
                    
                    //if rowmouseevent is 0 then proceed to for loop to remove element
                    if(rowmouseevent==0){
                    for(index=0 ;index < 8;index++){
                        index2=0;
                        info.remove(index2);
//                        index2+=1;
                        }
                    }
                    //else rowmousevent multiply by 9 and start removing element from the value after multiply
                    else{

                        int startingvalue = (rowmouseevent * 8);
                        for(index3=0 ;index3 < 8;index3++){
                            index2=startingvalue;
                            info.remove(startingvalue);

                            }
                        }
                    
                    //create new file writer and write data into file from list using for loop
                    FileWriter fw = new FileWriter(f);
                    int newsize = info.size();
                    int i;
                    for(i= 0;i<newsize;i++){
                        fw.write(info.get(i)+"\n");
                    }
                    fw.close();
                    
                    //after writing close this window and open viewbooking jframe
                    this.dispose();
                    viewBooking vb = new viewBooking(1);
                    vb.setVisible(true);
                    
                }
                //if rowmousevent is smaller than 0 then message will appear
                if(rowmouseevent<0){
                    JOptionPane.showMessageDialog(this,"Please Select a Row!");
                }
                
            }catch(Exception e){}
    }//GEN-LAST:event_deletebuttActionPerformed

    private void EditButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtActionPerformed
        //get selected row and coloumn from table when mouse click
        int rowmouseevent = jTable1.getSelectedRow(); 
        int coloumnevent = jTable1.getSelectedColumn();
        
        //if selected value is not -1 then close this window and open editdetails window and pass the variable to editdetails jframe
        if(rowmouseevent!=-1){
            dispose();
            new editdetails(rowmouseevent).setVisible(true);
        }
    }//GEN-LAST:event_EditButtActionPerformed

    private void backbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttActionPerformed
        // when button click it will close the window and open the main page
        
            dispose();
            main_page mp = new main_page();
            mp.setVisible(true);
        
    }//GEN-LAST:event_backbuttActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //get selected row from table when mouse click
        int rowmouseevent = jTable1.getSelectedRow();  
    }//GEN-LAST:event_jTable1MouseClicked

    private void receiptbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptbuttActionPerformed
        // get selected row from table when mouse click
        int rowmouseevent = jTable1.getSelectedRow(); 
        //if rowmouseevent is not -1 then proceed else show message
        if(rowmouseevent!=-1){
            new receiptui(rowmouseevent).setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this,"Please select a Data to Proceed!");
        }
        
    }//GEN-LAST:event_receiptbuttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewBooking(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditButt;
    private javax.swing.JButton backbutt;
    private javax.swing.JButton deletebutt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton receiptbutt;
    // End of variables declaration//GEN-END:variables
}
